// ═══════════════════════════════════════════
// GITHUB COMPILE SERVICE
// Uses GitHub API + Actions for free JAR builds
// ═══════════════════════════════════════════

const API = 'https://api.github.com';

// Store GitHub credentials in localStorage
export function getGitHubCreds() {
  if (typeof window === 'undefined') return null;
  try {
    return JSON.parse(localStorage.getItem('nova_github')) || null;
  } catch { return null; }
}

export function saveGitHubCreds(creds) {
  if (typeof window === 'undefined') return;
  localStorage.setItem('nova_github', JSON.stringify(creds));
}

export function clearGitHubCreds() {
  if (typeof window === 'undefined') return;
  localStorage.removeItem('nova_github');
}

// ═══════════════════════════════════════════
// GITHUB ACTIONS WORKFLOW
// ═══════════════════════════════════════════

function generateWorkflow(javaVersion = 17) {
  return `name: Build Plugin
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java ${javaVersion}
        uses: actions/setup-java@v4
        with:
          java-version: '${javaVersion}'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x gradlew || true

      - name: Build with Gradle
        run: |
          if [ -f "gradlew" ]; then
            ./gradlew build shadowJar --no-daemon
          else
            gradle build shadowJar --no-daemon
          fi

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: plugin-jar
          path: |
            build/libs/*.jar
            !build/libs/*-dev.jar
            !build/libs/*-sources.jar
          retention-days: 30
`;
}

// Minimal Gradle wrapper properties
function generateWrapperProps() {
  return `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-8.5-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`;
}

// Gradlew shell script
function generateGradlew() {
  return `#!/bin/sh
# Gradle startup script — auto-generated by Nova
APP_BASE_NAME=\`basename "$0"\`
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
exec java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
`;
}

// ═══════════════════════════════════════════
// API HELPERS
// ═══════════════════════════════════════════

async function githubFetch(path, token, options = {}) {
  const res = await fetch(`${API}${path}`, {
    ...options,
    headers: {
      'Authorization': `token ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub API ${res.status}: ${text}`);
  }
  return res.json();
}

// ═══════════════════════════════════════════
// MAIN FUNCTIONS
// ═══════════════════════════════════════════

// Verify token works
export async function verifyToken(token) {
  try {
    const user = await githubFetch('/user', token);
    return { valid: true, username: user.login, avatar: user.avatar_url };
  } catch {
    return { valid: false };
  }
}

// Create or get repo
export async function ensureRepo(token, repoName) {
  try {
    const repo = await githubFetch(`/user/repos`, token, {
      method: 'POST',
      body: JSON.stringify({
        name: repoName,
        description: 'Built with Nova AI Mod Creator',
        private: false,
        auto_init: true,
      }),
    });
    return { created: true, repo };
  } catch (err) {
    if (err.message.includes('422')) {
      // Repo already exists, get it
      const creds = getGitHubCreds();
      const repo = await githubFetch(`/repos/${creds.username}/${repoName}`, token);
      return { created: false, repo };
    }
    throw err;
  }
}

// Push all project files to repo
export async function pushFiles(token, owner, repoName, files, javaVersion = 17) {
  // Get the default branch SHA
  let sha;
  try {
    const ref = await githubFetch(`/repos/${owner}/${repoName}/git/ref/heads/main`, token);
    sha = ref.object.sha;
  } catch {
    // Try master branch
    const ref = await githubFetch(`/repos/${owner}/${repoName}/git/ref/heads/master`, token);
    sha = ref.object.sha;
  }

  // Get the tree SHA
  const commit = await githubFetch(`/repos/${owner}/${repoName}/git/commits/${sha}`, token);
  const treeSha = commit.tree.sha;

  // Build all file blobs
  const allFiles = { ...files };

  // Add workflow
  allFiles['.github/workflows/build.yml'] = generateWorkflow(javaVersion);

  // Add gradle wrapper properties
  allFiles['gradle/wrapper/gradle-wrapper.properties'] = generateWrapperProps();

  // Add gradlew
  allFiles['gradlew'] = generateGradlew();

  // Add .gitignore if missing
  if (!allFiles['.gitignore']) {
    allFiles['.gitignore'] = 'build/\n.gradle/\n*.class\n.idea/\n*.iml\nout/\n';
  }

  // Create tree entries
  const treeItems = [];
  for (const [path, content] of Object.entries(allFiles)) {
    const blob = await githubFetch(`/repos/${owner}/${repoName}/git/blobs`, token, {
      method: 'POST',
      body: JSON.stringify({
        content: typeof content === 'string' ? content : JSON.stringify(content),
        encoding: 'utf-8',
      }),
    });
    treeItems.push({
      path,
      mode: path === 'gradlew' ? '100755' : '100644',
      type: 'blob',
      sha: blob.sha,
    });
  }

  // Create new tree
  const newTree = await githubFetch(`/repos/${owner}/${repoName}/git/trees`, token, {
    method: 'POST',
    body: JSON.stringify({ base_tree: treeSha, tree: treeItems }),
  });

  // Create commit
  const newCommit = await githubFetch(`/repos/${owner}/${repoName}/git/commits`, token, {
    method: 'POST',
    body: JSON.stringify({
      message: 'Build via Nova AI',
      tree: newTree.sha,
      parents: [sha],
    }),
  });

  // Update ref
  try {
    await githubFetch(`/repos/${owner}/${repoName}/git/refs/heads/main`, token, {
      method: 'PATCH',
      body: JSON.stringify({ sha: newCommit.sha, force: true }),
    });
  } catch {
    await githubFetch(`/repos/${owner}/${repoName}/git/refs/heads/master`, token, {
      method: 'PATCH',
      body: JSON.stringify({ sha: newCommit.sha, force: true }),
    });
  }

  return newCommit;
}

// Check build status
export async function getBuildStatus(token, owner, repoName) {
  try {
    const runs = await githubFetch(
      `/repos/${owner}/${repoName}/actions/runs?per_page=1`,
      token
    );
    if (runs.workflow_runs.length === 0) return { status: 'none' };

    const run = runs.workflow_runs[0];
    return {
      status: run.status,          // queued, in_progress, completed
      conclusion: run.conclusion,  // success, failure, null
      id: run.id,
      url: run.html_url,
      started: run.created_at,
    };
  } catch {
    return { status: 'error' };
  }
}

// Get artifact download URL
export async function getArtifactUrl(token, owner, repoName, runId) {
  try {
    const artifacts = await githubFetch(
      `/repos/${owner}/${repoName}/actions/runs/${runId}/artifacts`,
      token
    );
    if (artifacts.artifacts.length === 0) return null;

    const jar = artifacts.artifacts.find(a => a.name === 'plugin-jar') || artifacts.artifacts[0];
    return {
      name: jar.name,
      size: jar.size_in_bytes,
      downloadUrl: jar.archive_download_url,
      expired: jar.expired,
    };
  } catch {
    return null;
  }
}

// Download artifact (returns blob)
export async function downloadArtifact(token, downloadUrl) {
  const res = await fetch(downloadUrl, {
    headers: { 'Authorization': `token ${token}` },
  });
  if (!res.ok) throw new Error('Download failed');
  return res.blob();
}
