// ═══════════════════════════════════════════
// MINECRAFT VERSION DATA
// ═══════════════════════════════════════════

export const MC_VERSIONS = [
  { value: '1.21.4', label: '1.21.4', apiVersion: '1.21', spigotApi: '1.21.4-R0.1-SNAPSHOT', java: 21, packFormat: 48 },
  { value: '1.21.3', label: '1.21.3', apiVersion: '1.21', spigotApi: '1.21.3-R0.1-SNAPSHOT', java: 21, packFormat: 48 },
  { value: '1.21.1', label: '1.21.1', apiVersion: '1.21', spigotApi: '1.21.1-R0.1-SNAPSHOT', java: 21, packFormat: 48 },
  { value: '1.20.6', label: '1.20.6', apiVersion: '1.20', spigotApi: '1.20.6-R0.1-SNAPSHOT', java: 21, packFormat: 41 },
  { value: '1.20.4', label: '1.20.4', apiVersion: '1.20', spigotApi: '1.20.4-R0.1-SNAPSHOT', java: 17, packFormat: 26 },
  { value: '1.20.2', label: '1.20.2', apiVersion: '1.20', spigotApi: '1.20.2-R0.1-SNAPSHOT', java: 17, packFormat: 18 },
  { value: '1.20.1', label: '1.20.1', apiVersion: '1.20', spigotApi: '1.20.1-R0.1-SNAPSHOT', java: 17, packFormat: 15 },
  { value: '1.19.4', label: '1.19.4', apiVersion: '1.19', spigotApi: '1.19.4-R0.1-SNAPSHOT', java: 17, packFormat: 13 },
  { value: '1.18.2', label: '1.18.2', apiVersion: '1.18', spigotApi: '1.18.2-R0.1-SNAPSHOT', java: 17, packFormat: 9 },
  { value: '1.17.1', label: '1.17.1', apiVersion: '1.17', spigotApi: '1.17.1-R0.1-SNAPSHOT', java: 16, packFormat: 7 },
  { value: '1.16.5', label: '1.16.5', apiVersion: '1.16', spigotApi: '1.16.5-R0.1-SNAPSHOT', java: 11, packFormat: 6 },
];

// ═══════════════════════════════════════════
// PLUGIN TEMPLATE
// ═══════════════════════════════════════════

export function generatePluginTemplate(projectName, packageName, mcVersion = '1.20.4') {
  const safeName = projectName.replace(/[^a-zA-Z0-9]/g, '');
  const pkg = packageName || `com.example.${safeName.toLowerCase()}`;
  const pkgPath = pkg.replace(/\./g, '/');
  const ver = MC_VERSIONS.find(v => v.value === mcVersion) || MC_VERSIONS[4];

  return {
    [`src/main/java/${pkgPath}/${safeName}.java`]: `package ${pkg};

import org.bukkit.plugin.java.JavaPlugin;
import lombok.Getter;

public class ${safeName} extends JavaPlugin {

    @Getter
    private static ${safeName} instance;

    @Override
    public void onEnable() {
        instance = this;
        saveDefaultConfig();
        getLogger().info("${safeName} has been enabled!");

        // Register commands
        // Register listeners
        // Initialize managers
    }

    @Override
    public void onDisable() {
        getLogger().info("${safeName} has been disabled!");
    }
}`,

    'src/main/resources/plugin.yml': `name: ${safeName}
version: 1.0.0
main: ${pkg}.${safeName}
api-version: '${ver.apiVersion}'
description: A Minecraft plugin created with Nova AI
author: NovaUser
commands: {}
permissions: {}`,

    'src/main/resources/config.yml': `# ${safeName} Configuration
# Minecraft ${mcVersion}
# Generated by Nova AI

settings:
  debug: false
  language: en_US`,

    'src/main/resources/languages/en_US.yml': `# English Language File
prefix: "&8[&a${safeName}&8] &7"
no-permission: "&cYou don't have permission to do that."
reload-success: "&aConfiguration reloaded successfully."`,

    'build.gradle': `plugins {
    id 'java'
    id 'io.freefair.lombok' version '8.6'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = '${pkg}'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(${ver.java})
    }
}

repositories {
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:${ver.spigotApi}'
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    implementation 'com.zaxxer:HikariCP:5.1.0'
}

shadowJar {
    archiveClassifier.set('')
    relocate 'com.zaxxer.hikari', '${pkg}.libs.hikari'
}

build.dependsOn shadowJar`,

    'settings.gradle': `rootProject.name = '${safeName}'`,
  };
}

// ═══════════════════════════════════════════
// DATAPACK TEMPLATE
// ═══════════════════════════════════════════

export function generateDatapackTemplate(projectName, _pkg, mcVersion = '1.20.4') {
  const safeName = projectName.replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();
  const ver = MC_VERSIONS.find(v => v.value === mcVersion) || MC_VERSIONS[4];

  return {
    'pack.mcmeta': JSON.stringify({
      pack: { pack_format: ver.packFormat, description: `${projectName} - Created with Nova AI` },
    }, null, 2),
    [`data/${safeName}/functions/main.mcfunction`]: `# ${projectName} - Main Function\n# Minecraft ${mcVersion}\n# Generated by Nova AI\n\nsay ${projectName} loaded!`,
    [`data/${safeName}/functions/tick.mcfunction`]: `# Runs every tick\n# Add tick logic here`,
    [`data/minecraft/tags/functions/load.json`]: JSON.stringify({ values: [`${safeName}:main`] }, null, 2),
    [`data/minecraft/tags/functions/tick.json`]: JSON.stringify({ values: [`${safeName}:tick`] }, null, 2),
  };
}

// ═══════════════════════════════════════════
// MOD TEMPLATE
// ═══════════════════════════════════════════

export function generateModTemplate(projectName, packageName, mcVersion = '1.20.4') {
  const safeName = projectName.replace(/[^a-zA-Z0-9]/g, '');
  const modId = safeName.toLowerCase();
  const pkg = packageName || `com.example.${modId}`;
  const pkgPath = pkg.replace(/\./g, '/');
  const ver = MC_VERSIONS.find(v => v.value === mcVersion) || MC_VERSIONS[4];

  return {
    [`src/main/java/${pkgPath}/${safeName}Mod.java`]: `package ${pkg};

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod("${modId}")
public class ${safeName}Mod {

    private static final Logger LOGGER = LogManager.getLogger();

    public ${safeName}Mod() {
        FMLJavaModLoadingContext.get().getModEventBus().addListener(this::setup);
    }

    private void setup(final FMLCommonSetupEvent event) {
        LOGGER.info("${safeName} initialized!");
    }
}`,

    'src/main/resources/META-INF/mods.toml': `modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="${modId}"
version="1.0.0"
displayName="${projectName}"
description="Created with Nova AI"`,

    'build.gradle': `plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.+'
}

version = '1.0.0'
group = '${pkg}'

java.toolchain.languageVersion = JavaLanguageVersion.of(${ver.java})

minecraft {
    mappings channel: 'official', version: '${mcVersion}'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:${mcVersion}-49.0.30'
}`,

    'settings.gradle': `pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://maven.minecraftforge.net/' }
    }
}
rootProject.name = '${safeName}'`,
  };
}

export const PROJECT_TYPES = {
  plugin: { label: 'Plugin (Spigot/Paper)', generator: generatePluginTemplate },
  datapack: { label: 'Datapack', generator: generateDatapackTemplate },
  mod: { label: 'Mod (Forge)', generator: generateModTemplate },
};
