// Default file templates for Java project types

export function generatePluginTemplate(projectName, packageName) {
  const safeName = projectName.replace(/[^a-zA-Z0-9]/g, '');
  const pkg = packageName || `com.example.${safeName.toLowerCase()}`;
  const pkgPath = pkg.replace(/\./g, '/');

  return {
    [`src/main/java/${pkgPath}/${safeName}.java`]: `package ${pkg};

import org.bukkit.plugin.java.JavaPlugin;
import lombok.Getter;

public class ${safeName} extends JavaPlugin {

    @Getter
    private static ${safeName} instance;

    @Override
    public void onEnable() {
        instance = this;
        saveDefaultConfig();
        getLogger().info("${safeName} has been enabled!");

        // Register commands
        // Register listeners
        // Initialize managers
    }

    @Override
    public void onDisable() {
        getLogger().info("${safeName} has been disabled!");
    }
}`,

    'src/main/resources/plugin.yml': `name: ${safeName}
version: 1.0.0
main: ${pkg}.${safeName}
api-version: '1.20'
description: A Minecraft plugin created with Nova AI
author: NovaUser
commands: {}
permissions: {}`,

    'src/main/resources/config.yml': `# ${safeName} Configuration
# Generated by Nova AI

settings:
  debug: false
  language: en_US`,

    'src/main/resources/languages/en_US.yml': `# English Language File
prefix: "&8[&a${safeName}&8] &7"
no-permission: "&cYou don't have permission to do that."
reload-success: "&aConfiguration reloaded successfully."`,

    'build.gradle': `plugins {
    id 'java'
    id 'io.freefair.lombok' version '8.6'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = '${pkg}'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.20.4-R0.1-SNAPSHOT'
    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    implementation 'com.zaxxer:HikariCP:5.1.0'
}

shadowJar {
    archiveClassifier.set('')
    relocate 'com.zaxxer.hikari', '${pkg}.libs.hikari'
}

build.dependsOn shadowJar`,

    'settings.gradle': `rootProject.name = '${safeName}'`,
  };
}

export function generateDatapackTemplate(projectName) {
  const safeName = projectName.replace(/[^a-zA-Z0-9_]/g, '').toLowerCase();

  return {
    'pack.mcmeta': JSON.stringify(
      {
        pack: {
          pack_format: 26,
          description: `${projectName} - Created with Nova AI`,
        },
      },
      null,
      2
    ),
    [`data/${safeName}/functions/main.mcfunction`]: `# ${projectName} - Main Function\n# Generated by Nova AI\n\nsay ${projectName} loaded!`,
    [`data/${safeName}/functions/tick.mcfunction`]: `# Runs every tick\n# Add tick logic here`,
    [`data/minecraft/tags/functions/load.json`]: JSON.stringify(
      { values: [`${safeName}:main`] },
      null,
      2
    ),
    [`data/minecraft/tags/functions/tick.json`]: JSON.stringify(
      { values: [`${safeName}:tick`] },
      null,
      2
    ),
  };
}

export function generateModTemplate(projectName, packageName) {
  const safeName = projectName.replace(/[^a-zA-Z0-9]/g, '');
  const modId = safeName.toLowerCase();
  const pkg = packageName || `com.example.${modId}`;
  const pkgPath = pkg.replace(/\./g, '/');

  return {
    [`src/main/java/${pkgPath}/${safeName}Mod.java`]: `package ${pkg};

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod("${modId}")
public class ${safeName}Mod {

    private static final Logger LOGGER = LogManager.getLogger();

    public ${safeName}Mod() {
        FMLJavaModLoadingContext.get().getModEventBus().addListener(this::setup);
    }

    private void setup(final FMLCommonSetupEvent event) {
        LOGGER.info("${safeName} initialized!");
    }
}`,

    'src/main/resources/META-INF/mods.toml': `modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="${modId}"
version="1.0.0"
displayName="${projectName}"
description="Created with Nova AI"`,

    'build.gradle': `plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '6.0.+'
}

version = '1.0.0'
group = '${pkg}'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.4'
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.4-49.0.30'
}`,

    'settings.gradle': `pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url 'https://maven.minecraftforge.net/' }
    }
}
rootProject.name = '${safeName}'`,
  };
}

export const PROJECT_TYPES = {
  plugin: { label: 'Plugin (Spigot/Paper)', generator: generatePluginTemplate },
  datapack: { label: 'Datapack', generator: generateDatapackTemplate },
  mod: { label: 'Mod (Forge)', generator: generateModTemplate },
};
